version: '3.8'

services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: always
    ports:
      - "2376:2376"
    networks:
      - jenkins-net

  my-jenkins:
    build: .                         # ใช้ Dockerfile ที่คุณสร้างไว้
    container_name: my-jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net
    depends_on:
      - jenkins-docker

volumes:
  jenkins_home:

networks:
  jenkins-net:
